/**
 * Shrimp character renderer — loads PNG images generated by Flux Dev.
 * 5 evolution stages × 3 moods = 15 images in public/characters/.
 */

export type Mood = 'happy' | 'neutral' | 'sad'
export type Stage = 1 | 2 | 3 | 4 | 5

const BASE_PATH = import.meta.env.BASE_URL + 'characters/'

export function renderShrimp(stage: Stage, mood: Mood): string {
  const src = `${BASE_PATH}stage${stage}-${mood}.png`
  return `<img src="${src}" alt="Stage ${stage} ${mood} shrimp" class="shrimp-img" draggable="false" />`
}

export function getMoodFromBehavior(consecutiveIgnored: number): Mood {
  if (consecutiveIgnored >= 3) return 'sad'
  if (consecutiveIgnored >= 1) return 'neutral'
  return 'happy'
}
